
package Client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LibraryServerService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:50001/cal?wsdl")
public class LibraryServerService
    extends Service
{

    private final static URL LIBRARYSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException LIBRARYSERVERSERVICE_EXCEPTION;
    private final static QName LIBRARYSERVERSERVICE_QNAME = new QName("http://server/", "LibraryServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:50001/cal?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIBRARYSERVERSERVICE_WSDL_LOCATION = url;
        LIBRARYSERVERSERVICE_EXCEPTION = e;
    }

    public LibraryServerService() {
        super(__getWsdlLocation(), LIBRARYSERVERSERVICE_QNAME);
    }

    public LibraryServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIBRARYSERVERSERVICE_QNAME, features);
    }

    public LibraryServerService(URL wsdlLocation) {
        super(wsdlLocation, LIBRARYSERVERSERVICE_QNAME);
    }

    public LibraryServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIBRARYSERVERSERVICE_QNAME, features);
    }

    public LibraryServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LibraryServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LibraryInterface
     */
    @WebEndpoint(name = "LibraryServerPort")
    public LibraryInterface getLibraryServerPort() {
        return super.getPort(new QName("http://server/", "LibraryServerPort"), LibraryInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LibraryInterface
     */
    @WebEndpoint(name = "LibraryServerPort")
    public LibraryInterface getLibraryServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "LibraryServerPort"), LibraryInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIBRARYSERVERSERVICE_EXCEPTION!= null) {
            throw LIBRARYSERVERSERVICE_EXCEPTION;
        }
        return LIBRARYSERVERSERVICE_WSDL_LOCATION;
    }

}
